// procurement-app/frontend/src/views/analytics/barriers/LanguageDetector.vue
<template>
  <div class="px-4 sm:px-6 lg:px-8 py-6 max-w-screen-xl mx-auto">

    <div class="mb-5 flex items-start justify-between gap-4 flex-wrap">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">Procurement Language Detector</h1>
        <p class="text-gray-500 text-sm mt-0.5">Paste any contract specification — AI-powered detection of SME-unfriendly language patterns</p>
      </div>
      <RouterLink to="/analytics/barriers" class="btn-secondary text-sm">← Back to Overview</RouterLink>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-2 gap-5">

      <!-- Input panel -->
      <div class="space-y-4">
        <div class="card p-5">
          <div class="flex items-center justify-between mb-2">
            <label class="font-semibold text-gray-900 text-sm">Contract Specification Text</label>
            <div class="flex gap-2">
              <button @click="loadExample" class="text-xs text-brand-600 hover:underline">Load example</button>
              <button @click="clearAll"    class="text-xs text-gray-400 hover:text-gray-600">Clear</button>
            </div>
          </div>
          <textarea
            v-model="specText"
            rows="18"
            class="input resize-none font-mono text-sm leading-relaxed"
            placeholder="Paste contract specification, ITT, or procurement notice text here…

Example:
The successful supplier must demonstrate a minimum of 7 years' relevant experience delivering similar projects to central government.

Annual turnover must be at least £2 million in each of the last 2 financial years.

Suppliers must hold ISO 9001 and Cyber Essentials Plus certification at the point of contract award.

This is an extension of the existing contract arrangement with our current supplier…"></textarea>
          <div class="flex items-center justify-between mt-2">
            <p class="text-xs text-gray-400">{{ wordCount }} words</p>
            <button @click="analyseText" :disabled="analysing || specText.trim().length < 20"
              class="btn-primary px-6"
              :class="analysing || specText.trim().length < 20 ? 'opacity-60 cursor-not-allowed' : ''">
              {{ analysing ? 'Analysing…' : '🔍 Analyse' }}
            </button>
          </div>
        </div>

        <!-- Score summary (only after analysis) -->
        <div v-if="result" class="card p-5"
          :class="result.risk_level === 'Low' ? 'bg-green-50 border border-green-200' : result.risk_level === 'Medium' ? 'bg-amber-50 border border-amber-200' : 'bg-red-50 border border-red-200'">
          <div class="flex items-center justify-between mb-3">
            <h3 class="font-semibold text-gray-900">Analysis Summary</h3>
            <span class="px-3 py-1 rounded-full text-sm font-bold"
              :class="result.risk_level === 'Low' ? 'bg-green-200 text-green-800' : result.risk_level === 'Medium' ? 'bg-amber-200 text-amber-800' : 'bg-red-200 text-red-800'">
              {{ result.risk_level }} Risk
            </span>
          </div>
          <div class="grid grid-cols-3 gap-3 text-center">
            <div>
              <p class="text-2xl font-extrabold" :class="result.overall_score >= 65 ? 'text-green-600' : result.overall_score >= 35 ? 'text-amber-600' : 'text-red-600'">
                {{ result.overall_score }}/100
              </p>
              <p class="text-xs text-gray-500 mt-0.5">SME-Friendliness</p>
            </div>
            <div>
              <p class="text-2xl font-extrabold text-gray-900">{{ result.barrier_count }}</p>
              <p class="text-xs text-gray-500 mt-0.5">Barrier Instances</p>
            </div>
            <div>
              <p class="text-2xl font-extrabold text-gray-900">{{ result.total_words }}</p>
              <p class="text-xs text-gray-500 mt-0.5">Words</p>
            </div>
          </div>
          <div class="mt-3 grid grid-cols-2 gap-3 text-sm">
            <div class="bg-white/60 rounded-lg p-2 text-center">
              <p class="text-xs text-gray-500">Reading Level</p>
              <p class="font-semibold text-gray-800">{{ result.readability?.level }}</p>
            </div>
            <div class="bg-white/60 rounded-lg p-2 text-center">
              <p class="text-xs text-gray-500">Avg Sentence</p>
              <p class="font-semibold text-gray-800">{{ result.readability?.avg_sentence_length }} words</p>
            </div>
          </div>
        </div>
      </div>

      <!-- Results panel -->
      <div class="space-y-4">

        <!-- Positive indicators (if any) -->
        <div v-if="result && result.positive_indicators?.length" class="card p-4 bg-green-50 border border-green-200">
          <h4 class="font-semibold text-green-800 text-sm mb-2">✅ Positive SME Indicators Found</h4>
          <div class="flex flex-wrap gap-2">
            <span v-for="pos in result.positive_indicators" :key="pos"
              class="px-2.5 py-1 bg-green-100 text-green-700 text-xs font-medium rounded-full">
              {{ pos }}
            </span>
          </div>
        </div>

        <!-- Barriers detected -->
        <div v-if="result && result.barriers_detected?.length" class="space-y-3">
          <h3 class="font-semibold text-gray-900">⚠️ Barriers Detected ({{ result.barriers_detected.length }})</h3>
          <div v-for="barrier in result.barriers_detected" :key="barrier.type"
            class="card p-4 border-l-4"
            :class="severityBorder(barrier.severity)">
            <div class="flex items-start justify-between gap-3 mb-2">
              <div class="flex items-center gap-2">
                <span class="px-2 py-0.5 text-xs font-bold rounded-full" :class="severityBadge(barrier.severity)">
                  {{ barrier.severity.toUpperCase() }}
                </span>
                <h4 class="font-semibold text-gray-900 text-sm">{{ barrier.label }}</h4>
              </div>
              <span class="text-xs text-gray-400 whitespace-nowrap">{{ barrier.count }} instance{{ barrier.count > 1 ? 's' : '' }}</span>
            </div>

            <!-- Matched text snippets -->
            <div class="flex flex-wrap gap-1.5 mb-3">
              <code v-for="match in barrier.matches" :key="match"
                class="px-2 py-0.5 text-xs rounded text-gray-700 font-mono"
                :class="barrier.severity === 'high' ? 'bg-red-50' : barrier.severity === 'medium' ? 'bg-amber-50' : 'bg-blue-50'">
                "{{ match }}"
              </code>
            </div>

            <!-- Suggestion -->
            <div class="bg-blue-50 border border-blue-100 rounded-lg p-3">
              <p class="text-xs font-semibold text-blue-700 mb-0.5">💡 Suggested Rewrite</p>
              <p class="text-xs text-blue-800 leading-relaxed">{{ barrier.suggestion }}</p>
            </div>
          </div>
        </div>

        <!-- Highlighted text -->
        <div v-if="result && result.highlighted_html" class="card p-5">
          <h4 class="font-semibold text-gray-900 text-sm mb-2">Highlighted Specification Text</h4>
          <div class="flex gap-3 text-xs mb-3 flex-wrap">
            <span class="flex items-center gap-1"><span class="w-3 h-3 rounded inline-block" style="background:#fecaca"></span> High severity</span>
            <span class="flex items-center gap-1"><span class="w-3 h-3 rounded inline-block" style="background:#fef08a"></span> Medium severity</span>
            <span class="flex items-center gap-1"><span class="w-3 h-3 rounded inline-block" style="background:#bfdbfe"></span> Low severity</span>
          </div>
          <div class="prose prose-sm max-w-none text-sm text-gray-700 leading-relaxed whitespace-pre-wrap font-mono bg-gray-50 p-4 rounded-lg overflow-y-auto max-h-80"
            v-html="result.highlighted_html"></div>
        </div>

        <!-- No result yet -->
        <div v-if="!result" class="card p-12 flex flex-col items-center justify-center text-center border-2 border-dashed border-gray-200">
          <div class="text-5xl mb-3">📝</div>
          <p class="font-medium text-gray-500">Paste specification text and click Analyse</p>
          <p class="text-sm text-gray-400 mt-1">The system will detect SME-unfriendly language patterns and suggest rewrites</p>
        </div>

      </div>
    </div>

    <!-- Examples -->
    <div class="card p-5 mt-5">
      <h3 class="font-semibold text-gray-900 mb-3">Common SME-Unfriendly Patterns</h3>
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
        <div v-for="ex in examples" :key="ex.label" class="rounded-xl border p-3" :class="ex.cls">
          <p class="text-xs font-bold mb-1" :class="ex.textCls">{{ ex.label }}</p>
          <p class="text-xs font-mono italic text-gray-700">"{{ ex.bad }}"</p>
          <p class="text-xs text-gray-500 mt-1">→ {{ ex.fix }}</p>
        </div>
      </div>
    </div>

  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { barriersApi } from '@/lib/api'

const specText  = ref('')
const result    = ref(null)
const analysing = ref(false)
const wordCount = computed(() => specText.value.trim().split(/\s+/).filter(Boolean).length)

const exampleText = `Supplier Requirements and Selection Criteria

The successful supplier must demonstrate a minimum of 7 years' relevant experience delivering similar managed service contracts to UK central government departments.

Annual turnover must be at least £3 million in each of the last 2 consecutive financial years. Relevant financial information will be verified through Companies House.

Suppliers must hold ISO 9001:2015, ISO 27001, and Cyber Essentials Plus certification at the point of contract award. Evidence of current CHAS registration is also required.

This contract is a renewal and continuation of our existing managed IT services arrangement. The incumbent supplier's infrastructure knowledge will be considered during evaluation.

The framework agreement will be used via a call-off mechanism under the Crown Commercial Service RM6111 Lot 3b. Only suppliers on this framework are eligible to submit responses.

Submissions must be received no later than 14 working days from the date of this notice. Late submissions will not be considered under any circumstances.`

function loadExample() { specText.value = exampleText }
function clearAll()    { specText.value = ''; result.value = null }

function severityBorder(sev) {
  return { high: 'border-red-400', medium: 'border-amber-400', low: 'border-blue-300' }[sev] || 'border-gray-300'
}
function severityBadge(sev) {
  return { high: 'bg-red-100 text-red-700', medium: 'bg-amber-100 text-amber-700', low: 'bg-blue-100 text-blue-700' }[sev] || 'bg-gray-100 text-gray-600'
}

async function analyseText() {
  if (!specText.value.trim() || specText.value.trim().length < 20) return
  analysing.value = true
  try {
    const res = await barriersApi.analyzeLanguage(specText.value)
    result.value = res.data
  } catch (e) {
    result.value = { error: e.response?.data?.detail || 'Analysis failed' }
  }
  analysing.value = false
}

const examples = [
  { label: 'Experience Requirement', bad: 'minimum 5 years experience', fix: 'Demonstrate capability through case studies', cls: 'bg-red-50 border-red-200', textCls: 'text-red-700' },
  { label: 'Turnover Threshold',     bad: 'annual turnover of at least £2M', fix: 'Proportionate financial assessment (PPN 11/20)', cls: 'bg-red-50 border-red-200', textCls: 'text-red-700' },
  { label: 'Framework Lock-in',      bad: 'via Crown Commercial Service framework only', fix: 'Consider open competition alongside framework', cls: 'bg-amber-50 border-amber-200', textCls: 'text-amber-700' },
  { label: 'Incumbent Language',     bad: 'continuation of existing contract arrangement', fix: 'Restate scope neutrally; avoid continuity signals', cls: 'bg-amber-50 border-amber-200', textCls: 'text-amber-700' },
  { label: 'Certification Required', bad: 'must hold ISO 9001 and Cyber Essentials Plus', fix: 'Accept equivalents; allow post-award attainment', cls: 'bg-amber-50 border-amber-200', textCls: 'text-amber-700' },
  { label: 'Short Timeline',         bad: '14 working days from publication', fix: 'Minimum 30 days for above-threshold contracts', cls: 'bg-blue-50 border-blue-200', textCls: 'text-blue-700' },
]
</script>

// procurement-app-react/src/components/analytics/LanguageDetector.tsx
import { useState } from 'react'
import {
  Box, Typography, TextField, Button, Paper, Chip,
  LinearProgress, Accordion, AccordionSummary, AccordionDetails,
} from '@mui/material'
import ExpandMoreIcon from '@mui/icons-material/ExpandMore'
import { motion, AnimatePresence } from 'framer-motion'
import { barriersApi } from '../../services/api'
import type { LanguageResult } from '../../types'

const EXAMPLE = `Supplier Requirements and Selection Criteria

The successful supplier must demonstrate a minimum of 7 years' relevant experience delivering similar managed service contracts to UK central government departments.

Annual turnover must be at least £3 million in each of the last 2 consecutive financial years.

Suppliers must hold ISO 9001:2015, ISO 27001, and Cyber Essentials Plus certification at the point of contract award.

This contract is a renewal and continuation of our existing managed IT services arrangement. The incumbent supplier's infrastructure knowledge will be considered during evaluation.

The framework agreement will be used via a call-off mechanism under the Crown Commercial Service RM6111 Lot 3b. Only suppliers on this framework are eligible to submit responses.`

const sevColor = (s: string) => s === 'high' ? '#721C24' : s === 'medium' ? '#856404' : '#1F3A5F'
const sevBg    = (s: string) => s === 'high' ? '#f8d7da' : s === 'medium' ? '#fff3cd' : '#e8edf3'

export function LanguageDetector() {
  const [text, setText] = useState('')
  const [result, setResult] = useState<LanguageResult | null>(null)
  const [loading, setLoading] = useState(false)

  const analyse = async () => {
    if (text.trim().length < 20) return
    setLoading(true)
    try {
      const { data } = await barriersApi.analyzeLanguage(text)
      setResult(data)
    } catch {}
    setLoading(false)
  }

  const riskColor = result?.risk_level === 'Low' ? '#155724' : result?.risk_level === 'Medium' ? '#856404' : '#721C24'
  const riskBg   = result?.risk_level === 'Low' ? '#d4edda' : result?.risk_level === 'Medium' ? '#fff3cd' : '#f8d7da'

  return (
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: '1fr 1fr' }, gap: 3 }}>
      {/* Input */}
      <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
        <Paper elevation={0} sx={{ p: 2.5, borderRadius: 3, border: '1px solid #e8edf3' }}>
          <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1.5 }}>
            <Typography sx={{ fontSize: 14, fontWeight: 600 }}>Contract Specification Text</Typography>
            <Box sx={{ display: 'flex', gap: 1 }}>
              <Button size="small" sx={{ fontSize: 11 }} onClick={() => setText(EXAMPLE)}>Load example</Button>
              <Button size="small" sx={{ fontSize: 11, color: '#6C757D' }} onClick={() => { setText(''); setResult(null) }}>Clear</Button>
            </Box>
          </Box>
          <TextField
            multiline rows={14} fullWidth value={text}
            onChange={e => setText(e.target.value)}
            placeholder="Paste contract specification, ITT, or procurement notice text here…"
            sx={{ '& textarea': { fontSize: 12, fontFamily: 'monospace', lineHeight: 1.6 } }}
          />
          <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mt: 1.5 }}>
            <Typography variant="caption" sx={{ color: '#6C757D' }}>
              {text.trim().split(/\s+/).filter(Boolean).length} words
            </Typography>
            <Button variant="contained" onClick={analyse} disabled={loading || text.trim().length < 20}
              sx={{ fontSize: 13 }}>
              {loading ? 'Analysing…' : '🔍 Analyse'}
            </Button>
          </Box>
        </Paper>

        {result && (
          <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}>
            <Paper elevation={0} sx={{ p: 2.5, borderRadius: 3, border: `1px solid ${riskColor}30`, bgcolor: riskBg }}>
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
                <Typography sx={{ fontSize: 14, fontWeight: 700 }}>Analysis Summary</Typography>
                <Chip label={`${result.risk_level} Risk`} size="small"
                  sx={{ bgcolor: riskColor, color: '#fff', fontWeight: 700, fontSize: 11 }} />
              </Box>
              <Box sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 1.5, textAlign: 'center' }}>
                {[
                  { label: 'SME-Friendliness', value: `${result.overall_score}/100`, color: result.overall_score >= 65 ? '#155724' : result.overall_score >= 35 ? '#856404' : '#721C24' },
                  { label: 'Barriers Found', value: result.barrier_count, color: '#1F3A5F' },
                  { label: 'Total Words', value: result.total_words, color: '#1F3A5F' },
                ].map(({ label, value, color }) => (
                  <Box key={label}>
                    <Typography sx={{ fontSize: 22, fontWeight: 900, color }}>{value}</Typography>
                    <Typography variant="caption" sx={{ color: '#6C757D' }}>{label}</Typography>
                  </Box>
                ))}
              </Box>
              <Box sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 1.5, mt: 2 }}>
                <Box sx={{ bgcolor: 'rgba(255,255,255,0.6)', borderRadius: 2, p: 1.5, textAlign: 'center' }}>
                  <Typography variant="caption" sx={{ color: '#6C757D' }}>Reading Level</Typography>
                  <Typography sx={{ fontSize: 13, fontWeight: 600 }}>{result.readability?.level}</Typography>
                </Box>
                <Box sx={{ bgcolor: 'rgba(255,255,255,0.6)', borderRadius: 2, p: 1.5, textAlign: 'center' }}>
                  <Typography variant="caption" sx={{ color: '#6C757D' }}>Avg Sentence</Typography>
                  <Typography sx={{ fontSize: 13, fontWeight: 600 }}>{result.readability?.avg_sentence_length} words</Typography>
                </Box>
              </Box>
            </Paper>
          </motion.div>
        )}
      </Box>

      {/* Results */}
      <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
        <AnimatePresence>
          {result ? (
            <motion.div key="results" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
              {result.positive_indicators?.length > 0 && (
                <Paper elevation={0} sx={{ p: 2, borderRadius: 3, border: '1px solid #c3e6cb', bgcolor: '#d4edda', mb: 2 }}>
                  <Typography sx={{ fontSize: 12, fontWeight: 700, color: '#155724', mb: 1 }}>✅ Positive SME Indicators</Typography>
                  <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.75 }}>
                    {result.positive_indicators.map(p => (
                      <Chip key={p} label={p} size="small"
                        sx={{ bgcolor: '#b8dfc9', color: '#155724', fontSize: 10, height: 20 }} />
                    ))}
                  </Box>
                </Paper>
              )}

              {result.barriers_detected?.length > 0 && (
                <Box>
                  <Typography sx={{ fontSize: 13, fontWeight: 700, mb: 1 }}>
                    ⚠️ Barriers Detected ({result.barriers_detected.length})
                  </Typography>
                  {result.barriers_detected.map((b, i) => (
                    <Accordion key={b.type} defaultExpanded={i === 0}
                      elevation={0} sx={{ border: `1px solid ${sevBg(b.severity)}`, borderRadius: '8px !important', mb: 1,
                        borderLeft: `4px solid ${sevColor(b.severity)}`, '&:before': { display: 'none' } }}>
                      <AccordionSummary expandIcon={<ExpandMoreIcon sx={{ fontSize: 18 }} />} sx={{ py: 0.5, minHeight: 0 }}>
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, flex: 1 }}>
                          <Chip label={b.severity.toUpperCase()} size="small"
                            sx={{ bgcolor: sevBg(b.severity), color: sevColor(b.severity), fontWeight: 700, fontSize: 10, height: 18 }} />
                          <Typography sx={{ fontSize: 12, fontWeight: 600 }}>{b.label}</Typography>
                          <Box sx={{ flex: 1 }} />
                          <Typography variant="caption" sx={{ color: '#6C757D', mr: 1 }}>
                            {b.count} instance{b.count > 1 ? 's' : ''}
                          </Typography>
                        </Box>
                      </AccordionSummary>
                      <AccordionDetails sx={{ pt: 0 }}>
                        <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5, mb: 1.5 }}>
                          {b.matches.map(m => (
                            <Box key={m} component="code" sx={{
                              px: 1, py: 0.25, bgcolor: sevBg(b.severity), borderRadius: 1,
                              fontSize: 11, fontFamily: 'monospace', color: sevColor(b.severity),
                            }}>
                              "{m}"
                            </Box>
                          ))}
                        </Box>
                        <Box sx={{ bgcolor: '#e8f4fd', border: '1px solid #bee5eb', borderRadius: 2, p: 1.5 }}>
                          <Typography variant="caption" sx={{ fontWeight: 700, color: '#2E75B6' }}>💡 Suggested Rewrite</Typography>
                          <Typography sx={{ fontSize: 12, color: '#1F3A5F', mt: 0.5, lineHeight: 1.6 }}>{b.suggestion}</Typography>
                        </Box>
                      </AccordionDetails>
                    </Accordion>
                  ))}
                </Box>
              )}

              {result.highlighted_html && (
                <Paper elevation={0} sx={{ p: 2.5, borderRadius: 3, border: '1px solid #e8edf3' }}>
                  <Typography sx={{ fontSize: 13, fontWeight: 600, mb: 1.5 }}>Highlighted Specification</Typography>
                  <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap', mb: 1.5 }}>
                    {[['#fecaca', 'High'], ['#fef08a', 'Medium'], ['#bfdbfe', 'Low']].map(([color, label]) => (
                      <Box key={label} sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                        <Box sx={{ width: 12, height: 12, borderRadius: '3px', bgcolor: color }} />
                        <Typography variant="caption" sx={{ color: '#6C757D' }}>{label} severity</Typography>
                      </Box>
                    ))}
                  </Box>
                  <Box
                    sx={{ maxHeight: 300, overflowY: 'auto', bgcolor: '#f8f9fa', p: 2, borderRadius: 2,
                      fontFamily: 'monospace', fontSize: 12, lineHeight: 1.7, color: '#1F3A5F',
                      whiteSpace: 'pre-wrap', '& mark': { borderRadius: '3px', px: '2px' } }}
                    dangerouslySetInnerHTML={{ __html: result.highlighted_html }}
                  />
                </Paper>
              )}
            </motion.div>
          ) : (
            <motion.div key="empty" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
              <Paper elevation={0} sx={{ p: 8, borderRadius: 3, border: '2px dashed #e8edf3', textAlign: 'center', bgcolor: '#fafbfc' }}>
                <Typography sx={{ fontSize: 48, mb: 2 }}>📝</Typography>
                <Typography sx={{ fontSize: 14, fontWeight: 600, color: '#6C757D' }}>
                  Paste specification text and click Analyse
                </Typography>
                <Typography variant="body2" sx={{ mt: 1, color: '#9ca3af' }}>
                  Detects SME-unfriendly language patterns and suggests rewrites
                </Typography>
              </Paper>
            </motion.div>
          )}
        </AnimatePresence>
      </Box>
    </Box>
  )
}
